/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import estoqueprod.Eletronico;
import estoqueprod.GerenciarProdutos;
import estoqueprod.Movel;
import estoqueprod.Perecivel;
import estoqueprod.Produto;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Jackson Souza
 */
public class FrmCadastrar extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmCadastrar
     */
    public FrmCadastrar() {
        initComponents();
        pnEletronico.setVisible(false);
        pnPerecivel.setVisible(false);
        pnMovel.setVisible(false);
    }
    int codTipoProduto = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnMovel = new javax.swing.JPanel();
        lMaterial = new javax.swing.JLabel();
        txtMaterialTipo = new javax.swing.JTextField();
        pnPerecivel = new javax.swing.JPanel();
        dtValidade = new javax.swing.JFormattedTextField();
        lValidade = new javax.swing.JLabel();
        cbRefrigerado = new javax.swing.JCheckBox();
        pnEletronico = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPotencia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbEficiencia = new javax.swing.JComboBox();
        cbVoltagem = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        lNome = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JTextField();
        lFabricante = new javax.swing.JLabel();
        txtFabricanteProduto = new javax.swing.JTextField();
        lPreco = new javax.swing.JLabel();
        txtPrecoProduto = new javax.swing.JTextField();
        lQuantidade = new javax.swing.JLabel();
        txtQuantidadeProduto = new javax.swing.JTextField();
        lTipoProduto = new javax.swing.JLabel();
        cbTipoProduto = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        btCancelar = new javax.swing.JButton();
        btAvancar = new javax.swing.JButton();

        setTitle("Cadastrar Produto");
        setPreferredSize(new java.awt.Dimension(600, 485));

        jPanel1.setPreferredSize(new java.awt.Dimension(540, 485));

        pnMovel.setBorder(javax.swing.BorderFactory.createTitledBorder("Móvel"));

        lMaterial.setText("Tipo de Material");

        javax.swing.GroupLayout pnMovelLayout = new javax.swing.GroupLayout(pnMovel);
        pnMovel.setLayout(pnMovelLayout);
        pnMovelLayout.setHorizontalGroup(
            pnMovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMovelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaterialTipo)
                    .addGroup(pnMovelLayout.createSequentialGroup()
                        .addComponent(lMaterial)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnMovelLayout.setVerticalGroup(
            pnMovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMovelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lMaterial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaterialTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnPerecivel.setBorder(javax.swing.BorderFactory.createTitledBorder("Perecível"));

        try {
            dtValidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lValidade.setText("Data de Validade");

        cbRefrigerado.setText("Refrigerado");

        javax.swing.GroupLayout pnPerecivelLayout = new javax.swing.GroupLayout(pnPerecivel);
        pnPerecivel.setLayout(pnPerecivelLayout);
        pnPerecivelLayout.setHorizontalGroup(
            pnPerecivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPerecivelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPerecivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPerecivelLayout.createSequentialGroup()
                        .addComponent(lValidade)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPerecivelLayout.createSequentialGroup()
                        .addGroup(pnPerecivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbRefrigerado, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                            .addComponent(dtValidade))
                        .addContainerGap())))
        );
        pnPerecivelLayout.setVerticalGroup(
            pnPerecivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPerecivelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(lValidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dtValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbRefrigerado)
                .addGap(12, 12, 12))
        );

        pnEletronico.setBorder(javax.swing.BorderFactory.createTitledBorder("Eletrónico"));

        jLabel1.setText("Voltagem");

        jLabel3.setText("Classificação de eficiência");

        cbEficiencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CLASSIFIQUE A EFICIENCIA", "A", "B", "C", "D", "E" }));
        cbEficiencia.setToolTipText("");

        cbVoltagem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE A VOLTAGEM", "110 V", "220 V", "Bivolt" }));

        jLabel2.setText("Potência");

        javax.swing.GroupLayout pnEletronicoLayout = new javax.swing.GroupLayout(pnEletronico);
        pnEletronico.setLayout(pnEletronicoLayout);
        pnEletronicoLayout.setHorizontalGroup(
            pnEletronicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEletronicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnEletronicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(cbVoltagem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbEficiencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPotencia))
                .addContainerGap())
        );
        pnEletronicoLayout.setVerticalGroup(
            pnEletronicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEletronicoLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbVoltagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEficiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lNome.setText("Produto Nome");

        txtNomeProduto.setName("txtNomeProduto"); // NOI18N

        lFabricante.setText("Fabricante do Produto");

        txtFabricanteProduto.setName("txtFabricanteProduto"); // NOI18N

        lPreco.setText("Preço");

        txtPrecoProduto.setName("txtPrecoProduto"); // NOI18N

        lQuantidade.setText("Quantidade");

        txtQuantidadeProduto.setName("txtQuantidadeProduto"); // NOI18N

        lTipoProduto.setText("Tipo de Produto");

        cbTipoProduto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE O TIPO DO PRODUTO", "Eletronico", "Movel", "Perecivel" }));
        cbTipoProduto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoProdutoItemStateChanged(evt);
            }
        });

        btCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btCancelar.setText("CANCELAR / VOLTAR");
        btCancelar.setName("btAvancarCadastro"); // NOI18N
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btAvancar.setBackground(new java.awt.Color(255, 255, 255));
        btAvancar.setText("AVANÇAR");
        btAvancar.setName("btAvancarCadastro"); // NOI18N
        btAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAvancarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAvancar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeProduto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lFabricante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFabricanteProduto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lPreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecoProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lQuantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantidadeProduto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lTipoProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipoProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnMovel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnPerecivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnEletronico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNome)
                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lFabricante)
                    .addComponent(txtFabricanteProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPreco)
                    .addComponent(lQuantidade)
                    .addComponent(txtQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTipoProduto)
                    .addComponent(cbTipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnEletronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnPerecivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnMovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAvancarActionPerformed
        GerenciarProdutos gr = new GerenciarProdutos();
        try {
            int codigoP = gr.tamanhoLista()+1;
            String nomeP = txtNomeProduto.getText();
            String fabricanteP = txtFabricanteProduto.getText();
            int quantidadeP = Integer.parseInt(txtQuantidadeProduto.getText());
            double precoP = Double.parseDouble(txtPrecoProduto.getText());

            if(cbTipoProduto.getSelectedIndex() == 1 ){
                int tipoCodigoP = 1;
                String voltagemP = cbVoltagem.getSelectedItem().toString();
                String potenciaP = txtPotencia.getText();
                String stringEficiencia = cbEficiencia.getSelectedItem().toString();
                char eficienciaP = stringEficiencia.charAt(0);

                Produto p = new Eletronico(codigoP, nomeP, fabricanteP, quantidadeP, precoP, tipoCodigoP, voltagemP, potenciaP, eficienciaP);
                gr.adicionar(p);
                limpaTudo();

                JOptionPane.showMessageDialog(null,"Produto Eletronico cadastrado com sucesso.","SUCESSO", JOptionPane.INFORMATION_MESSAGE);
            } 
            if(cbTipoProduto.getSelectedIndex() == 2 ){
                int tipoCodigoP = 2;
                String materialP = txtMaterialTipo.getText();

                Produto p = new Movel(codigoP, nomeP, fabricanteP, quantidadeP, precoP, tipoCodigoP, materialP);
                gr.adicionar(p);
                limpaTudo();           

                JOptionPane.showMessageDialog(null,"Produto Movel cadastrado com sucesso.","SUCESSO", JOptionPane.INFORMATION_MESSAGE);
            } 
            if(cbTipoProduto.getSelectedIndex() == 3 ){
                int tipoCodigoP = 3;
                boolean refrigeradoP;
                if(cbRefrigerado.isSelected()){
                    refrigeradoP = true;
                } else {
                    refrigeradoP = false;
                }

                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("d/MM/yyyy");
                String validadeString = dtValidade.getText();
                LocalDate validadeP = LocalDate.parse(validadeString, formatter);

                Produto p = new Perecivel(codigoP, nomeP, fabricanteP, quantidadeP, precoP, tipoCodigoP, validadeP, refrigeradoP);
                gr.adicionar(p);
                limpaTudo();
                JOptionPane.showMessageDialog(null,"Produto Perecivel cadastrado com sucesso.","SUCESSO", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            if(cbTipoProduto.getSelectedIndex() == 0){
                JOptionPane.showMessageDialog(null,"TIPO DE PRODUTO NÃO SELECIONADO.","ERROR", JOptionPane.WARNING_MESSAGE);
            }else {
                JOptionPane.showMessageDialog(null, "CAMPO EM BRANCO OU DADOS DIGITADOS INCORRETOS.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btAvancarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void cbTipoProdutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoProdutoItemStateChanged
        if(cbTipoProduto.getSelectedIndex() == 1 ){
            pnEletronico.setVisible(true);
            pnPerecivel.setVisible(false);
            pnMovel.setVisible(false);
        }
        if(cbTipoProduto.getSelectedIndex() == 2 ){
            pnMovel.setVisible(true);
            pnEletronico.setVisible(false);
            pnPerecivel.setVisible(false);
        }
        if(cbTipoProduto.getSelectedIndex() == 3 ){
            pnPerecivel.setVisible(true);
            pnEletronico.setVisible(false);
            pnMovel.setVisible(false);
        }
    }//GEN-LAST:event_cbTipoProdutoItemStateChanged

    public void limpaTudo(){
        txtNomeProduto.setText("");
        txtFabricanteProduto.setText("");
        txtQuantidadeProduto.setText("");
        txtPrecoProduto.setText("");
        cbTipoProduto.setSelectedIndex(0);
        pnEletronico.setVisible(false);
        cbVoltagem.setSelectedIndex(0);
        txtPotencia.setText("");
        cbEficiencia.setSelectedIndex(0);
        pnPerecivel.setVisible(false);
        dtValidade.setText("  /  /    ");
        cbRefrigerado.setSelected(false);
        pnMovel.setVisible(false);
        txtMaterialTipo.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAvancar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JComboBox cbEficiencia;
    private javax.swing.JCheckBox cbRefrigerado;
    private javax.swing.JComboBox cbTipoProduto;
    private javax.swing.JComboBox cbVoltagem;
    private javax.swing.JFormattedTextField dtValidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lFabricante;
    private javax.swing.JLabel lMaterial;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lPreco;
    private javax.swing.JLabel lQuantidade;
    private javax.swing.JLabel lTipoProduto;
    private javax.swing.JLabel lValidade;
    private javax.swing.JPanel pnEletronico;
    private javax.swing.JPanel pnMovel;
    private javax.swing.JPanel pnPerecivel;
    private javax.swing.JTextField txtFabricanteProduto;
    private javax.swing.JTextField txtMaterialTipo;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtPotencia;
    private javax.swing.JTextField txtPrecoProduto;
    private javax.swing.JTextField txtQuantidadeProduto;
    // End of variables declaration//GEN-END:variables
}
