/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import estoqueprod.GerenciarProdutos;
import estoqueprod.ModeloTabelaProdutos;
import javax.swing.JOptionPane;

/**
 *
 * @author Marketing
 */
public class FrmMovimentacaoVenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmMovimentacaoVenda
     */
    public FrmMovimentacaoVenda() {
        initComponents();
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lNome = new javax.swing.JLabel();
        lFabricante = new javax.swing.JLabel();
        lQuantidade = new javax.swing.JLabel();
        lPreco = new javax.swing.JLabel();
        lCodigo = new javax.swing.JLabel();
        label01 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        lDoisPontos1 = new javax.swing.JLabel();
        lDoisPontos2 = new javax.swing.JLabel();
        lDoisPontos3 = new javax.swing.JLabel();
        lDoisPontos4 = new javax.swing.JLabel();
        lPreco1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnVender = new javax.swing.JButton();
        labelAleatorio = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();

        setTitle("VENDER PRODUTO");

        lNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lNome.setText("XXXX");

        lFabricante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lFabricante.setText("XXXX");

        lQuantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lQuantidade.setText("0000");

        lPreco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lPreco.setText("0000");

        lCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lCodigo.setText("0000");

        label01.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label01.setText("CODIGO DO PRODUTO");

        label2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label2.setText("NOME DO PRODUTO");

        label3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label3.setText("FABRICANTE DO PRODUTO");

        label4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label4.setText("QUANTIDADE EM ESTOQUE");

        label5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label5.setText("PREÇO DO PRODUTO");

        lDoisPontos1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lDoisPontos1.setText(" : ");

        lDoisPontos2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lDoisPontos2.setText(" : ");

        lDoisPontos3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lDoisPontos3.setText(" : ");

        lDoisPontos4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lDoisPontos4.setText(" : ");

        lPreco1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lPreco1.setText(" : ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label01)
                    .addComponent(label2)
                    .addComponent(label3)
                    .addComponent(label4)
                    .addComponent(label5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lDoisPontos2)
                    .addComponent(lDoisPontos1)
                    .addComponent(lDoisPontos3)
                    .addComponent(lDoisPontos4)
                    .addComponent(lPreco1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNome)
                    .addComponent(lCodigo)
                    .addComponent(lFabricante)
                    .addComponent(lQuantidade)
                    .addComponent(lPreco))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lDoisPontos1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lDoisPontos2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lDoisPontos3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lDoisPontos4)
                        .addGap(10, 10, 10)
                        .addComponent(lPreco1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lCodigo)
                            .addComponent(label01))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lNome)
                            .addComponent(label2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lFabricante)
                            .addComponent(label3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lQuantidade)
                            .addComponent(label4))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lPreco)
                            .addComponent(label5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVender.setText("REALIZAR VENDA");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        labelAleatorio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelAleatorio.setText("DIGITE A QUANTIDADE QUE DESEJA VENDER : ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAleatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelAleatorio))
                    .addComponent(txtValor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProdutos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        GerenciarProdutos gr = new GerenciarProdutos();
        int venderPCodigo = Integer.parseInt(lCodigo.getText());
        int venderPQuantidade = Integer.parseInt(txtValor.getText());
        int estoquePQuantidade = Integer.parseInt(lQuantidade.getText());
        double venderPValorUnit = Double.parseDouble(lPreco.getText());
        
        double valorFinal = venderPQuantidade * venderPValorUnit;
        
        try {
            if(estoquePQuantidade > venderPQuantidade){
                gr.venderProduto(venderPCodigo, venderPQuantidade);
                JOptionPane.showMessageDialog(null, "Venda realizada com sucesso, valor total : " + valorFinal, "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                carregarTabela();
                limpaLabels();
            } else {
                  JOptionPane.showMessageDialog(null, "verifique a quantidade de produtos selecionados e a disponibilidade em estoque.\nPedido com quantidade acima do nosso estoque.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Verifique a disponibilidade do produto.", "ERROR", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnVenderActionPerformed

    private void tabelaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutosMouseClicked
        int index = tabelaProdutos.getSelectedRow();
        GerenciarProdutos gr = new GerenciarProdutos();
        ModeloTabelaProdutos modelo = new ModeloTabelaProdutos(gr.getProdutos());

        int codigo = Integer.parseInt(modelo.getValueAt(index, 0).toString());
        String nome = modelo.getValueAt(index, 1).toString();
        String fabricante = modelo.getValueAt(index, 2).toString();
        int quantidade = Integer.parseInt(modelo.getValueAt(index, 3).toString());
        double preco = Double.parseDouble(modelo.getValueAt(index, 4).toString());

        lCodigo.setText(Integer.toString(codigo));
        lNome.setText(nome);
        lFabricante.setText(fabricante);
        lQuantidade.setText(Integer.toString(quantidade));
        lPreco.setText(Double.toString(preco));
    }//GEN-LAST:event_tabelaProdutosMouseClicked

    private void carregarTabela(){
        GerenciarProdutos gr = new GerenciarProdutos();
        
        ModeloTabelaProdutos modelo = new ModeloTabelaProdutos(gr.getProdutos());
        
        tabelaProdutos.setModel(modelo);
    }
    
    public void limpaLabels(){
        lCodigo.setText("0000");
        lNome.setText("XXXX");
        lFabricante.setText("XXXX");
        lQuantidade.setText("0000");
        lPreco.setText("0000");
        txtValor.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVender;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lCodigo;
    private javax.swing.JLabel lDoisPontos1;
    private javax.swing.JLabel lDoisPontos2;
    private javax.swing.JLabel lDoisPontos3;
    private javax.swing.JLabel lDoisPontos4;
    private javax.swing.JLabel lFabricante;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lPreco;
    private javax.swing.JLabel lPreco1;
    private javax.swing.JLabel lQuantidade;
    private javax.swing.JLabel label01;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel labelAleatorio;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
